src/main/java/com/odorgan/model/ToDo.java
package com.odorgan.model;

import java.util.Date;

import javax.persistence.*;
import javax.validation.constraints.Size;

import org.springframework.format.annotation.DateTimeFormat;

@Entity
@Table(name = "todo_list")
public class ToDo {
	
	@Id
	@Column(name="id")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
	protected Long id;
	
	@Column(name="username")
    protected String username;
	
	@Size(min=6, message="Enter at least 6 characters")
	private String description;
	
	@DateTimeFormat(pattern = "dd/MM/yyyy")
	@Temporal(TemporalType.DATE)
	@Column(name="target_date")
	private Date targetDate;
	
	@Column(name="is_done")
	private boolean isDone;
	
    public void setId(Long id) {
        this.id = id;
    }
    public Long getId() {
        return id;
    }
    
    public void setUsername(String username) {
    	this.username = username;
    }
    public String getUsername() {
        return username;
    }
    
	public String getDescription() {
		return description;
	}
	public void setDescription(String description) {
		this.description = description;
	}
	
	public Date getTargetDate() {
		return targetDate;
	}
	public void setTargetDate(Date targetDate) {
		this.targetDate = targetDate;
	}
	
	public boolean isDone() {
		return isDone;
	}
	public void setDone(boolean isDone) {
		this.isDone = isDone;
	}
	
	@Override
	public String toString() {
		return String.format("toString - ToDo [id=%s, username=%s, description=%s, targetDate=%s, isDone=%s]", 
												id, username, description, targetDate, isDone);
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		ToDo other = (ToDo) obj;
		if (id != other.id)
			return false;
		return true;
	}
	
	
}

src/main/java/com/odorgan/controller/ToDoController.java
package com.odorgan.controller;

import java.text.SimpleDateFormat;
import java.util.Date;

import javax.validation.Valid;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.propertyeditors.CustomDateEditor;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.WebDataBinder;
import org.springframework.web.bind.annotation.InitBinder;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import com.odorgan.model.ToDo;
import com.odorgan.service.ToDoServiceImpl;

@Controller
public class ToDoController {

	@Autowired
	ToDoServiceImpl service;

	@InitBinder
	protected void initBinder(WebDataBinder binder) {
		SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
		binder.registerCustomEditor(Date.class, new CustomDateEditor(dateFormat, false));
	}

	@RequestMapping(value = "/todo-list", method = RequestMethod.GET)
	public String listToDos(ModelMap model) {
		model.addAttribute("todos", service.retrieveToDos(retrieveLoggedInUsername()));
		model.addAttribute("tab2", "active");
		return "todo-list";
	}

	private String retrieveLoggedInUsername() {
		Object principal = SecurityContextHolder.getContext().getAuthentication().getPrincipal();

		if (principal instanceof UserDetails) {
			return ((UserDetails) principal).getUsername();
		}

		return principal.toString();
	}

	@RequestMapping(value = "/add-todo", method = RequestMethod.GET)
	public String addToDo(ModelMap model) {
		model.addAttribute("toDo", new ToDo());
		model.addAttribute("tab2", "active");
		return "todo";
	}

	@RequestMapping(value = "/add-todo", method = RequestMethod.POST)
	public String addToDo(ModelMap model, @ModelAttribute("toDo") @Valid ToDo todo, BindingResult result) {
		if (result.hasErrors()) {
			return "todo";
		}
		todo.setUsername(retrieveLoggedInUsername());
		System.out.println(todo.toString());
		service.saveToDo(todo);
		model.clear();
		return "redirect:todo-list";
	}

	@RequestMapping(value = "/delete-todo", method = RequestMethod.GET)
	public String deleteToDo(ModelMap model, @RequestParam int id) {
		ToDo todo = service.retrieveToDo(id);
		if (todo.getUsername().equalsIgnoreCase(retrieveLoggedInUsername())) {
			service.deleteToDo(id);
			model.clear();
		}
		return "redirect:todo-list";
	}

	@RequestMapping(value = "/update-todo", method = RequestMethod.GET)
	public String updateToDo(ModelMap model, @RequestParam int id) {
		ToDo todo = service.retrieveToDo(id);
		if (todo.getUsername().equalsIgnoreCase(retrieveLoggedInUsername())) {
			model.addAttribute("toDo", todo);
		}
		model.addAttribute("tab2", "active");
		return "todo";
	}
	

	@RequestMapping(value = "/update-todo", method = RequestMethod.POST)
	public String updateToDo(ModelMap model, @ModelAttribute("toDo") @Valid ToDo todo, BindingResult result) {
		ToDo dbTodo = service.retrieveToDo(todo.getId());
		if (dbTodo.getUsername().equalsIgnoreCase(retrieveLoggedInUsername())) {
			todo.setDone(!todo.isDone());
			service.saveToDo(todo);
		}
		dbTodo.setDescription(todo.getDescription());
		dbTodo.setTargetDate(todo.getTargetDate());
		if (model.get("complete") == "true") {
			dbTodo.setDone(true);
		}
		service.saveToDo(dbTodo);
		return "redirect:todo-list";
	}

	@RequestMapping(value = "/complete-todo", method = RequestMethod.GET)
	public String completeToDo(ModelMap model, @RequestParam int id) {
		ToDo todo = service.retrieveToDo(id);
		if (todo.getUsername().equalsIgnoreCase(retrieveLoggedInUsername())) {
			todo.setDone(!todo.isDone());
			service.saveToDo(todo);
		}
		return "redirect:todo-list";
	}

}

src/main/webapp/WEB-INF/views/error.jsp
<%@ include file="common/header.jspf"%>
<%@ include file="common/navigation.jspf"%>

<div class="container">
	<p>Application has encountered an error...</p>
</div>

<%@ include file="common/footer.jspf"%>

src/main/webapp/WEB-INF/views/login.jsp
<%@ include file="common/header.jspf"%>
<%@ include file="common/navigation.jspf"%>
<div class="container">
	<div class="row">
		<div class="col-lg-4"></div>
		<div class="col-lg-4">
			<c:if test="${not empty error}">
				<div class="error text-danger">${error}</div>
			</c:if>
			<c:if test="${not empty logout}">
				<div class="msg">${logout}</div>
			</c:if>
			<form:form action="/login" method="POST">
				<fieldset class="form-group">
					<label for="username">Name</label> <input name="username"
						type="text" id="username" class="form-control" />
				</fieldset>
				<fieldset class="form-group">
					<label>Password</label> <input name="password" type="password"
						id="password" class="form-control" />
				</fieldset>
				<div>
					<button type="submit" class="btn btn-success">Submit</button>
					<a class="text-info" href="/register">New user? Register here.</a>
				</div>
<%-- 				<input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}"/> --%>
			</form:form>
		</div>

		<div class="col-lg-4"></div>
	</div>
</div>


<%@ include file="common/footer.jspf"%>

src/main/webapp/WEB-INF/views/register.jsp
<%@ include file="common/header.jspf"%>
<%@ include file="common/navigation.jspf"%>
<div class="container">
	<div class="row">
		<div class="col-lg-4"></div>
		<div class="col-lg-4">
			<form:form method="POST" modelAttribute="userForm"
				class="form-signin">
				<h2 class="form-signin-heading">Create your account</h2>
				<spring:bind path="username">
					<div class="form-group ${status.error ? 'has-error' : ''}">
						<form:input type="text" path="username" class="form-control"
							placeholder="Username" autofocus="true"></form:input>
						<form:errors path="username"></form:errors>
					</div>
				</spring:bind>
				
				<spring:bind path="firstname">
					<div class="form-group ${status.error ? 'has-error' : ''}">
						<form:input type="text" path="firstname" class="form-control"
							placeholder="First Name" autofocus="true"></form:input>
						<form:errors path="firstname"></form:errors>
					</div>
				</spring:bind>
				
				<spring:bind path="surname">
					<div class="form-group ${status.error ? 'has-error' : ''}">
						<form:input type="text" path="surname" class="form-control"
							placeholder="Surname" autofocus="true"></form:input>
						<form:errors path="surname"></form:errors>
					</div>
				</spring:bind>

				<spring:bind path="password">
					<div class="form-group ${status.error ? 'has-error' : ''}">
						<form:input type="password" path="password" class="form-control"
							placeholder="Password"></form:input>
						<form:errors path="password"></form:errors>
					</div>
				</spring:bind>

				<spring:bind path="passwordConfirm">
					<div class="form-group ${status.error ? 'has-error' : ''}">
						<form:input type="password" path="passwordConfirm"
							class="form-control" placeholder="Confirm your password"></form:input>
						<form:errors path="passwordConfirm"></form:errors>
					</div>
				</spring:bind>

				<button class="btn btn-lg btn-primary btn-block" type="submit">Submit</button>
				<a class="text-info" href="/login">Already Registered? Login here.</a>
			</form:form>
		</div>
		<div class="col-lg-4"></div>
	</div>
</div>
<!-- /container -->
<%@ include file="common/footer.jspf"%>

src/main/webapp/WEB-INF/views/todo-list.jsp
<%@ include file="common/header.jspf"%>
<%@ include file="common/navigation.jspf"%>
<div class="container">
	<div class="row">
		<div class="col-sm-2"></div>
		<div class="col-sm-8">
			<h1>Your To-Do List</h1>
			<table class="table table-striped">
				<thead>
					<tr>
						<th>Description</th>
						<th>Target Date</th>
						<th>Completed?</th>
						<th></th>
					</tr>
				</thead>
				<tbody>
					<c:forEach items="${todos}" var="todo">
						<tr class=${todo.done == true ? "success" : ""}>
							<td>${todo.description}</td>
							<td><fmt:formatDate pattern="dd/MM/yyyy"
									value="${todo.targetDate}" /></td>
							<td>${todo.done}</td>
							<td>
								<div class="btn-group">
									<a class="btn btn-success" 
										href="complete-todo?id=${todo.id}">Complete?</a>
									<a class="btn btn-primary"
										href="/update-todo?id=${todo.id}">Update</a> 
									<a class="btn btn-danger" id="btnDelete"
										href="/delete-todo?id=${todo.id}">Delete</a>
								</div>
							</td>
						</tr>
					</c:forEach>
				</tbody>
			</table>
			<div>
				<a class="btn btn-success" href="/add-todo">Add</a>
			</div>
		</div>
		<div class="col-sm-2"></div>
	</div>
</div>

<%@ include file="common/footer.jspf"%>

src/main/webapp/WEB-INF/views/todo.jsp
<%@ include file="common/header.jspf"%>
<%@ include file="common/navigation.jspf"%>

<div class="container">
	<div class="row">
		<div class="col-lg-2"></div>
		<div class="col-lg-8">
			<h1>Manage your To-Dos</h1>
			<form:form method="post" commandName="toDo">

				<form:hidden path="id" />

				<fieldset class="form-group">
					<form:label path="description">Description</form:label>
					<form:input path="description" type="text" class="form-control"
						required="required" />
					<form:errors path="description" cssClass="text-warning" />
				</fieldset>

				<fieldset class="form-group">
					<form:label path="targetDate">Target Date</form:label>
					<form:input path="targetDate" type="date" class="form-control"
						required="required" />
					<form:errors path="targetDate" cssClass="text-warning" />
				</fieldset>

				<input class="btn btn-success" type="submit" value="Save" />

			</form:form>
		</div>
		<div class="col-lg-2"></div>
	</div>
</div>

<%@ include file="common/footer.jspf"%>

src/main/webapp/WEB-INF/views/welcome.jsp
<%@ include file="common/header.jspf"%>
<%@ include file="common/navigation.jspf"%>

<div class="container">
	<h1>Welcome ${firstname}.</h1>
	<p>
		Here is your <a href="/todo-list">To-Do list.</a>
	</p>
</div>

<%@ include file="common/footer.jspf"%>